name = "ITensorTreeEntropyTools"
uuid = "dcff5701-e2bf-4ed4-b6f5-e5810ab8d5c3"
authors = ["Ryan Levy <rlevy@flatironinstitute.org>"]
version = "0.1.0"

[deps]
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensorNetworks = "2919e153-833c-4bdc-8836-1ea460a35fc7"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[compat]
ITensorMPS = "0.3.2"
ITensorNetworks = "0.11.24"
ITensors = "0.7"
julia = "1.10"
