name = "ITensorEntropyTools"
uuid = "f9fb0810-3969-484c-b54e-62935ba8ba22"
authors = ["Ryan Levy <rlevy@flatironinstitute.org>"]
version = "0.1.0"

[deps]
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[compat]
ITensorMPS = "0.3.2"
ITensors = "0.7"
julia = "1.10"
